### ISSUE TITLE
CSS image url rewrite with cache buster won't work if controller is not mounted under root

### ISSUE THREAD

**Issue by marano** [rstacruz/sinatra-assetpack#141]
If config.ru mounts a controller under a context, different from root, assetpack won't replace the URL in the css files with the cache buster bit.
The reason for this is that assetpack internal "served" list doesn't include the context in the path.

Example:

``` ruby
# config.ru
map '/context' do
  run Controller
end
```

``` ruby
# controller.rb

class Controller < Sinatra::Base
  assets {
    serve '/img', :from => 'lib/img'
  }
end
```

``` css
// example.css
a {
  background-image: url( /context/img/a.png );
}
```
